"""Lesson content, strategies 01-20. Merged with the strategy catalog by
scripts/generate_learn_assets.py; prose must never quote default values
(the generator injects the real defaults from strategies.json)."""

LESSONS_A = {
    # ------------------------------------------------------------------ #
    # Momentum & Trend Following
    # ------------------------------------------------------------------ #
    "01_rsi_mean_reversion": {
        "difficulty": 1,
        "summary": "Buy when the market is panicking (RSI below 30), sell when it's euphoric (RSI above 70). The classic 'fade the extremes' starter strategy.",
        "idea": "Prices whip back and forth around a fair value. When RSI drops below 30 the recent move has been unusually one-sided — and in a normal market, gravity pulls price back. This account buys the panic and exits the euphoria.",
        "how": [
            "Compute RSI(14) on every closed candle.",
            "RSI < 30 (oversold): buy with nearly all available cash (95% default).",
            "Hold while RSI wanders between 30 and 70 — no fiddling.",
            "RSI > 70 (overbought): sell the whole position.",
            "No stop-loss, no take-profit: the RSI thresholds are the entire rulebook.",
        ],
        "params": {
            "rsi_period": {"what": "How many candles RSI looks back.", "effect": "Shorter = more reactive, more false signals. Longer = smoother, later entries."},
            "rsi_buy": {"what": "RSI level that counts as oversold and triggers the buy.", "effect": "Lower = only extreme panics bought, fewer but better-bounce entries."},
            "rsi_sell": {"what": "RSI level that counts as overbought and triggers the sell.", "effect": "Lower = exits earlier with profit locked in, but misses late legs."},
        },
        "strengths": [
            "Simple, transparent, and easy to reason about.",
            "Buys exactly when everyone else is scared — good entries in ranging markets.",
            "Two parameters, no curve-fitting knobs.",
        ],
        "weaknesses": [
            "In a strong downtrend it catches falling knives: oversold keeps getting more oversold.",
            "Sells at RSI 70, which in a raging uptrend is far too early.",
            "No trend filter — it fades trends as happily as it fades noise.",
        ],
        "when": ["Works best when BTC is range-bound (chop between clear levels).", "Suffers most in strong directional phases — both up (early exits) and down (early buys)."],
        "mistakes": [
            "Reading 'RSI 25' as a guaranteed bounce — it's a stretched rubber band, not a promise.",
            "Loosening the sell threshold to 'let winners run' — that turns it into a different (trend) strategy.",
            "Forgetting it's long-only: in a crash this account just buys the whole way down.",
        ],
        "watch": [
            "Position badge: it should be long right after big red candles, flat right after big green ones.",
            "Compare its curve with strategy 02 — one fades moves, the other chases them.",
        ],
        "concepts": ["rsi", "mean_reversion", "oscillator", "long_only", "support_resistance"],
        "related": ["24_zscore_mean_reversion", "06_bollinger_mean_reversion", "02_dual_ema_crossover"],
    },
    "02_dual_ema_crossover": {
        "difficulty": 1,
        "summary": "The most famous trend signal in trading: when the fast EMA crosses above the slow one, buy; when it crosses back below, sell.",
        "idea": "A fast moving average represents today's mood, a slow one last month's. When the fast line overtakes the slow line, momentum has shifted up — the trend follower's cue to join.",
        "how": [
            "Track EMA(9) (fast) and EMA(21) (slow) of closes.",
            "Fast crosses ABOVE slow: buy with available cash.",
            "Ride while fast stays above slow.",
            "Fast crosses BELOW slow: sell everything.",
            "Classic trend-following: late entries, no targets, exits only on trend reversal.",
        ],
        "params": {
            "fast": {"what": "The quick EMA that leads.", "effect": "Smaller = crosses sooner with more whipsaws."},
            "slow": {"what": "The EMA that defines the prevailing mood.", "effect": "Larger = fewer, later, higher-quality crosses."},
        },
        "strengths": [
            "Captures the meat of sustained trends automatically.",
            "Zero subjectivity — the rule either fired or it didn't.",
            "Works on every timeframe and asset class.",
        ],
        "weaknesses": [
            "Whipsaw hell in sideways markets: buy the cross, sell the cross, repeat at a loss.",
            "Entries are late — you buy after the move already started.",
            "The two EMAs are highly correlated, so 'two confirmations' is really one opinion.",
        ],
        "when": ["Trending markets with follow-through (BTC trending phases).", "Chop and tight ranges produce repeated small losses."],
        "mistakes": [
            "Switching EMA lengths after losses ('optimizing' into curve-fitting).",
            "Expecting it to call tops — it confirms trends, it doesn't predict them.",
            "Judging it over a few trades; trend systems need many cycles to show their edge.",
        ],
        "watch": [
            "Strategy state shows the EMA values each tick — you can see the gap widen in trends.",
            "Pair mentally with strategy 01: when 01 loses, 02 usually wins (and vice versa).",
        ],
        "concepts": ["ema", "trend", "momentum", "warmup"],
        "related": ["04_triple_moving_average", "03_macd_histogram_reversal", "20_ema_ribbon_consensus"],
    },
    "03_macd_histogram_reversal": {
        "difficulty": 2,
        "summary": "A momentum-change radar: MACD is the gap between fast and slow momentum, and crossing its signal line marks the turn.",
        "idea": "MACD subtracts a 26-period EMA from a 12-period one, so it rises while short-term momentum outruns long-term momentum. The 9-EMA signal line smooths it; their crossing is a cleaner, momentum-flavoured cousin of the EMA crossover.",
        "how": [
            "Compute MACD line (12−26 EMAs), signal (9 EMA of MACD) and histogram.",
            "Histogram turns positive (MACD crossed above signal): buy.",
            "Hold while momentum stays with you.",
            "Histogram turns negative (MACD crossed below signal): sell.",
            "The histogram sign, not its size, drives decisions.",
        ],
        "params": {
            "fast": {"what": "Fast EMA of MACD.", "effect": "Smaller = more sensitive to short-term moves."},
            "slow": {"what": "Slow EMA of MACD.", "effect": "Larger = smoother, slower momentum baseline."},
            "signal": {"what": "Smoothing of the MACD line itself.", "effect": "Smaller = signal crosses more often (more trades)."},
        },
        "strengths": [
            "Combines trend and momentum in one number.",
            "The signal cross filters out tiny meaningless momentum ripples.",
            "Very widely followed — its signals attract real money.",
        ],
        "weaknesses": [
            "Laggy: built on EMAs of EMAs, so turns arrive after price turned.",
            "In flat markets the histogram saws around zero, whipsawing the account.",
            "Doesn't distinguish strong vs weak trends (no ADX-style filter).",
        ],
        "when": ["Moderate, persistent trends.", "Bad in low-volatility chop and around major news reversals."],
        "mistakes": [
            "Reading histogram HEIGHT as strength — this strategy only uses its sign.",
            "Forgetting the defaults (12/26/9) are 1970s stock parameters, not BTC gospel.",
            "Expecting early reversals; MACD confirms after the fact by design.",
        ],
        "watch": ["State shows the histogram value with its sign — it flips only on crosses.", "Long stretches of near-zero histogram = chop; expect whipsaws then."],
        "concepts": ["macd", "momentum", "ema", "trend"],
        "related": ["02_dual_ema_crossover", "19_trix_momentum", "39_multi_indicator_consensus"],
    },
    "04_triple_moving_average": {
        "difficulty": 1,
        "summary": "The trend-stack strategy: only buy when SMA 20 > 50 > 200 — the whole market structure agrees the trend is up.",
        "idea": "One moving average is an opinion; three nested ones are a hierarchy. When the short sits above the medium above the long, every timeframe agrees: dips are being bought in an uptrend. When the 20 falls under the 50, the first layer of the stack has broken.",
        "how": [
            "Compute SMA(20), SMA(50) and SMA(200) of closes.",
            "All three aligned 20 > 50 > 200: buy (the full stack is bullish).",
            "Stay long while the stack holds.",
            "SMA20 drops below SMA50: sell — the stack's foundation cracked.",
            "SMA200 needs 200 candles before this account can even think (warm-up 200).",
        ],
        "params": {
            "fast": {"what": "Shortest average, fastest to react.", "effect": "Smaller = stack breaks sooner, both entries and exits."},
            "mid": {"what": "Middle average, medium trend.", "effect": "The line whose breach triggers the exit."},
            "slow": {"what": "Longest average, macro regime line.", "effect": "Larger = more history needed, more stable regime filter."},
        },
        "strengths": [
            "Extremely robust: nested SMAs rarely give contradictory signals.",
            "Stays in the biggest trends for a long time (the 20/50 breach is a late, strong exit).",
            "A teachable model of 'multiple timeframe' thinking.",
        ],
        "weaknesses": [
            "Very late entries and exits — gives back large parts of moves.",
            "200-candle warm-up means ~2 days of 15m candles before first signal.",
            "In a long bear, the stack never aligns and the account just sits in cash (fine, but idle).",
        ],
        "when": ["Secular bull phases and strong recoveries.", "Dead money in multi-month chop where the stack flips constantly."],
        "mistakes": [
            "Using it to time exact bottoms — it buys AFTER the turn is confirmed.",
            "Overriding exits because 'the 200 still looks fine' — the rule is the 20/50 break.",
            "Comparing its flat bear-market curve to dip-buyers without noting it held cash.",
        ],
        "watch": ["You can see the three averages in strategy state on aligned days.", "Note how long it held during the last uptrend vs how quickly it exited."],
        "concepts": ["sma", "trend", "support_resistance", "warmup"],
        "related": ["02_dual_ema_crossover", "20_ema_ribbon_consensus", "35_chandelier_trend_ride"],
    },
    "05_supertrend_atr": {
        "difficulty": 2,
        "summary": "One ATR-scaled line that acts as trend and trailing stop at once: buy the flip up, ride until it flips down or the stop is hit.",
        "idea": "Supertrend draws a line at the price midpoint ± 3×ATR. While price stays above it, the line creeps up underneath — a trailing stop that breathes with volatility. When price closes through it, the whole regime has flipped.",
        "how": [
            "Compute Supertrend from ATR(10) with a ×3 multiplier.",
            "Direction flips from bearish to bullish: buy.",
            "Hold; the Supertrend line is now your trailing stop, updated every candle.",
            "Exit when price closes below the stop line or the line flips bearish.",
            "Live state stores the stop and direction each tick.",
        ],
        "params": {
            "atr_period": {"what": "Lookback for the ATR that sizes the bands.", "effect": "Shorter = stop hugs price tighter, exits sooner."},
            "multiplier": {"what": "How many ATRs the band sits from price.", "effect": "Higher = wider stop, fewer shake-outs, bigger giveback. Lower = tigher, more whipsaws."},
        },
        "strengths": [
            "A genuine trailing stop: winners run, losses get cut early.",
            "ATR scaling means the stop adapts to BTC's changing mood.",
            "Very few parameters, highly visual logic.",
        ],
        "weaknesses": [
            "A single sharp candle against you can flip the line and exit at the worst spot.",
            "In chop, stops are hit repeatedly — death by a thousand small losses.",
            "No profit target: profits depend entirely on the trailing mechanism.",
        ],
        "when": ["Clean trending phases with normal volatility.", "Bad in whipsaw ranges and news-spike candles."],
        "mistakes": [
            "Treating the flip as a prediction — it's a reaction to what already happened.",
            "Tightening the multiplier to 2 'for less giveback' without expecting more exits.",
            "Ignoring that gaps/spikes can blow through any stop — paper or real.",
        ],
        "watch": ["State shows supertrend_stop and direction — compare stop to price each tick.", "The stop should climb with price in trends and sit above price in falls."],
        "concepts": ["supertrend", "atr", "trailing_stop", "trend"],
        "related": ["15_parabolic_sar", "35_chandelier_trend_ride", "41_volatility_regime_switcher"],
    },
    "13_adx_dmi_trend": {
        "difficulty": 2,
        "summary": "Trend trading with a strength requirement: +DI over −DI is only tradeable when ADX proves the trend is actually strong.",
        "idea": "Most crossover systems fail because they trade weak trends. ADX/DMI separates the question: WHO leads (+DI vs −DI) and HOW STRONGLY (ADX). This account only buys when the bulls take the lead in a trend strong enough to be worth joining.",
        "how": [
            "Compute ADX(14), +DI and −DI each candle.",
            "Buy only when +DI crosses above −DI AND ADX ≥ 25 (strong trend, fresh direction).",
            "Hold while +DI leads.",
            "Sell when −DI takes over, or when ADX fades below 20 (the trend is dying of weakness).",
            "The ADX fade-exit is the special sauce: it leaves before the turn completes.",
        ],
        "params": {
            "period": {"what": "Lookback for ADX/DMI.", "effect": "Standard 14 balances speed and stability."},
            "adx_min": {"what": "Minimum ADX to accept a new long.", "effect": "Higher = only powerful trends traded, far fewer signals."},
        },
        "strengths": [
            "Filters out the weak trends that kill naive crossovers.",
            "Explicit strength-based exit (ADX fade) as well as direction-based.",
            "Well-researched, institutional-grade indicator family.",
        ],
        "weaknesses": [
            "ADX is slow — it confirms strength after the move is obvious.",
            "Complex math, hard for beginners to debug by eye.",
            "Strong trends eventually fade; the ADX exit can still give back profit.",
        ],
        "when": ["Sustained directional markets with momentum.", "Ranges produce few signals — ADX stays low and the account waits (correctly)."],
        "mistakes": [
            "Buying every +DI/−DI cross without checking ADX (that's the whole point of the filter).",
            "Expecting ADX to predict — it measures what already is.",
            "Using ADX < 25 as a sell signal — this bot only exits on ADX < 20 or direction flip.",
        ],
        "watch": ["State prints ADX, +DI, −DI every tick — watch ADX climb during strong trends.", "During calm chop ADX should hover low and the account should stay flat."],
        "concepts": ["adx", "trend", "momentum", "breakout"],
        "related": ["17_aroon_trend", "05_supertrend_atr", "39_multi_indicator_consensus"],
    },
    "14_ichimoku_cloud": {
        "difficulty": 3,
        "summary": "The Japanese all-in-one system: price above the cloud with Tenkan over Kijun = buy; back inside the cloud or a failed cross = out.",
        "idea": "Ichimoku shows trend direction (the cloud), momentum (Tenkan/Kijun cross) and future support/resistance (the shifted cloud) in one picture. Trading it is trading a complete world-view rather than a single indicator.",
        "how": [
            "Compute Tenkan(9), Kijun(26), and the cloud (Senkou A/B, shifted 26).",
            "Buy when close is above the cloud TOP and Tenkan > Kijun.",
            "Hold while the picture stays bullish.",
            "Sell when close falls back below the cloud bottom, or Tenkan crosses below Kijun.",
            "Inside the cloud = no man's land: the account never initiates there.",
        ],
        "params": {
            "tenkan": {"what": "Fast conversion line period.", "effect": "Shorter = quicker momentum turns."},
            "kijun": {"what": "Base line period — the 'value' line.", "effect": "The mid-term anchor; its cross with Tenkan triggers exits."},
            "senkou_b": {"what": "Second cloud boundary period (52).", "effect": "Longer = thicker, more meaningful cloud."},
            "displacement": {"what": "How far the cloud is shifted forward.", "effect": "Shows future support/resistance; 26 is standard."},
        },
        "strengths": [
            "Combines trend, momentum and levels into one coherent system.",
            "The cloud acts as a dynamic support/resistance map.",
            "Very popular in crypto — its levels are self-watched by many traders.",
        ],
        "weaknesses": [
            "Complex: 4+ parameters and several sub-signals to reconcile.",
            "Slow: needs 80 candles warm-up and its signals lag.",
            "Cloud computations with displacement are unintuitive to debug.",
        ],
        "when": ["Clean trends where price travels outside the cloud.", "Awful inside clouds and when the cloud is flat/overlapping."],
        "mistakes": [
            "Buying a Tenkan/Kijun cross while price is INSIDE the cloud — this strategy refuses to.",
            "Ignoring that a thick cloud is stronger resistance/support than a thin one.",
            "Mixing Ichimoku timeframes (using daily settings on 15m bars without thought).",
        ],
        "watch": ["State doesn't print the cloud — check the Market screen overlay when available.", "It should be long during cloud-top rallies and flat inside clouds."],
        "concepts": ["ichimoku", "trend", "support_resistance", "breakout"],
        "related": ["04_triple_moving_average", "05_supertrend_atr", "33_pivot_point_bounce"],
    },
    "15_parabolic_sar": {
        "difficulty": 2,
        "summary": "Pure trend-chasing dots: the SAR flip is both the entry signal and a stop that accelerates as the trend ages.",
        "idea": "Parabolic SAR dots sit under price in uptrends and above in downtrends, accelerating toward price the longer the trend runs. The flip is a complete 'trend changed' statement — this strategy buys flips and lets the dot do all exit thinking.",
        "how": [
            "Compute SAR with step 0.02 and maximum 0.2.",
            "SAR flips from above price to below: buy.",
            "Hold while price stays above the SAR.",
            "SAR flips back above price: sell — no second opinions.",
            "The SAR effectively tightens each candle, so exits arrive faster as trends age.",
        ],
        "params": {
            "step": {"what": "How fast the SAR accelerates per candle.", "effect": "Higher = stop chases price harder, exits sooner and more often."},
            "maximum": {"what": "Cap on the acceleration factor.", "effect": "Higher cap = tighter end-of-trend stops; standard 0.2."},
        },
        "strengths": [
            "Total objectivity: one dot decides everything.",
            "Trailing behaviour protects profits as trends mature.",
            "Very simple state to watch live (dot vs price).",
        ],
        "weaknesses": [
            "Notorious whipsawing in sideways markets — dots flip constantly.",
            "Acceleration means the exit can be very close to price in long trends (early shake-outs).",
            "No consideration of volume or strength.",
        ],
        "when": ["Long smooth trends — the SAR shines when direction persists.", "Chop is its kryptonite."],
        "mistakes": [
            "Using SAR as a top-caller; it flips only after price passes it.",
            "Raising 'step' to 0.03 for tighter stops without expecting more whipsaws.",
            "Forgetting warm-up 15: it needs a full SAR cycle to be meaningful.",
        ],
        "watch": ["Live state holds the SAR value; compare its distance from price.", "Distance shrinks as trends age — a sign the exit is approaching."],
        "concepts": ["psar", "trailing_stop", "trend", "momentum"],
        "related": ["05_supertrend_atr", "35_chandelier_trend_ride", "02_dual_ema_crossover"],
    },
    "16_roc_momentum": {
        "difficulty": 1,
        "summary": "Momentum burst, measured bluntly: buy when price moved +2% over 12 candles and sell when that push fully decays.",
        "idea": "ROC is pure percentage change — no smoothing, no cleverness. A 12-candle ROC above +2% means a real push just happened; momentum traders bet pushes continue. When ROC falls back to 0%, the push is spent and this account leaves.",
        "how": [
            "Compute ROC(12): % change of close vs 12 candles ago.",
            "ROC ≥ +2%: buy (fresh momentum burst).",
            "Ride while momentum persists.",
            "ROC ≤ 0%: sell — the entire burst has been given back.",
            "Exit at exactly zero: no profit target, momentum decay is the only exit.",
        ],
        "params": {
            "period": {"what": "Lookback for the % change.", "effect": "Shorter = fresher bursts, noisier; longer = smoother trend-ish momentum."},
            "entry_pct": {"what": "Momentum strength required to buy.", "effect": "Higher = only explosive moves traded (fewer, stronger entries)."},
            "exit_pct": {"what": "Momentum level that ends the trade.", "effect": "At 0 it holds until the whole burst decays; above 0 locks profit earlier."},
        },
        "strengths": [
            "Dead simple and transparent — one percentage.",
            "Catches violent impulsive moves early (crypto's speciality).",
            "Exit rule directly measures the bet ('momentum continues') failing.",
        ],
        "weaknesses": [
            "Buys AFTER a 2% pop — vulnerable to buying local tops.",
            "No trend context: a +2% bounce in a bear market also triggers it.",
            "Zero-exit gives back everything if momentum decays slowly.",
        ],
        "when": ["Volatile up-impulses (breakouts, short squeezes).", "Slow grind markets never reach +2% in 12 candles — account sits idle."],
        "mistakes": [
            "Assuming ROC predicts — it measures the recent past.",
            "Treating the 2% default as sacred; it's just a parameter.",
            "Expecting it to hold through pullbacks — the rule exits at exactly 0%.",
        ],
        "watch": ["State shows ROC% — see it spike on green candles.", "It should buy only after visible bursts, not during quiet climbs."],
        "concepts": ["roc", "momentum", "breakout", "trend"],
        "related": ["10_donchian_breakout", "28_volume_spike_breakout", "02_dual_ema_crossover"],
    },
    "17_aroon_trend": {
        "difficulty": 2,
        "summary": "A freshness meter for highs and lows: buy when new highs are recent and dominant, sell when new lows take over.",
        "idea": "Aroon asks one question: how long ago did price make its highest/lowest point of the window? Aroon Up ≈ 100 means the high happened just now — the trend is young and alive. Stale extremes mean the trend died. Trading Aroon is trading trend-freshness instead of price.",
        "how": [
            "Compute Aroon Up/Down over 25 candles.",
            "Buy when Aroon Up crosses above Aroon Down while Up ≥ 70 (fresh high, new momentum).",
            "Hold while Up leads.",
            "Sell when Aroon Down crosses above Up.",
            "Note: no strength filter on exit — any Down takeover ends the ride.",
        ],
        "params": {
            "period": {"what": "Lookback for counting candles since the last high/low.", "effect": "Shorter = fresher definitions of 'new'."},
            "strong": {"what": "Aroon level required at entry.", "effect": "Higher = only very recent highs qualify (higher conviction, fewer trades)."},
        },
        "strengths": [
            "Measures trend age, which crossovers don't.",
            "Clean, easy-to-read scale (0-100 both directions).",
            "Catches trends while they're still young-ish.",
        ],
        "weaknesses": [
            "In a fast pullback inside an uptrend, Down can take over and exit prematurely.",
            "Reads only high/low recency — no price, no volume.",
            "Whipsaws when highs/lows alternate rapidly.",
        ],
        "when": ["Steady trends with periodic fresh extremes.", "Bad in tight ranges where highs/lows alternate constantly."],
        "mistakes": [
            "Buying whenever Up > 70 without the cross — the cross (takeover) is the trigger.",
            "Thinking 100 means 'about to reverse' — it means 'just made a high'.",
            "Ignoring that 25 is a short window: it's a tactical, not strategic, trend tool.",
        ],
        "watch": ["State shows Up and Down — they should sit near 100 on fresh highs.", "When both drop below 50, the market has no trend and the account should be flat."],
        "concepts": ["aroon", "trend", "momentum", "breakout"],
        "related": ["13_adx_dmi_trend", "02_dual_ema_crossover", "16_roc_momentum"],
    },
    "18_heikin_ashi_trend": {
        "difficulty": 2,
        "summary": "The no-wick trade: three clean Heikin-Ashi bullish bars in a row means relentless buying — buy the streak, sell the mirror.",
        "idea": "Heikin-Ashi candles average price into smooth blocks. A body-only bullish bar (no lower wick) means buyers never lost control all period. Three in a row is a streak of pure domination — the bot joins the streak and leaves when sellers produce their own three-bar streak.",
        "how": [
            "Convert every candle to Heikin-Ashi form.",
            "Wait for 3 consecutive bullish bars with NO lower wick: buy.",
            "Hold while bullish structure continues.",
            "3 consecutive bearish bars with no upper wick: sell.",
            "Bar 3 of the bearish streak is the exit — it confirms sellers took over.",
        ],
        "params": {
            "confirm_bars": {"what": "How many clean bars must line up.", "effect": "More = higher conviction, later entries/exits. Fewer = faster, noisier."},
        },
        "strengths": [
            "Beautifully visual — even a beginner can 'see' the signal on a chart.",
            "The streak requirement filters single-bar noise.",
            "Symmetrical entry/exit logic is easy to verify.",
        ],
        "weaknesses": [
            "Smoothing hides raw price: HA bars lag reality by design.",
            "3-bar streaks in quiet chop are common and fake.",
            "No volume or volatility context.",
        ],
        "when": ["Strong directional waves.", "Chop creates short false streaks in both directions."],
        "mistakes": [
            "Reading raw candles as Heikin-Ashi — the whole point is the transformed version.",
            "Counting wicks on the body instead of open/low equality.",
            "Expecting early exits; the 3-bar requirement means giving back some of the turn.",
        ],
        "watch": ["Trades should cluster in waves — multiple trades per trend, not singles.", "Flat during wick-heavy candles (normal pullbacks create wicks)."],
        "concepts": ["heikin_ashi", "trend", "candlestick", "momentum"],
        "related": ["31_engulfing_reversal", "02_dual_ema_crossover", "15_parabolic_sar"],
    },
    "19_trix_momentum": {
        "difficulty": 3,
        "summary": "Momentum so filtered it only sees the deepest swings: triple-smoothed EMA rate-of-change, traded on signal crosses.",
        "idea": "TRIX triple-smooths price (EMA of EMA of EMA), then measures that ultra-smooth line's rate of change. Every layer of smoothing strips noise; what remains is the market's deepest momentum pulse. Crossing its own signal line is a major, slow, reliable turn.",
        "how": [
            "Compute TRIX(15): % change of triple-EMA.",
            "Smooth it again into a 9-period signal line.",
            "TRIX crosses ABOVE signal: buy.",
            "Hold while TRIX leads.",
            "TRIX crosses BELOW signal: sell.",
        ],
        "params": {
            "period": {"what": "EMA length used three times.", "effect": "Larger = even smoother, even slower, fewer signals."},
            "signal": {"what": "Smoothing of the TRIX line.", "effect": "Smaller = more crosses; larger = fewer, later."},
        },
        "strengths": [
            "Extremely robust against noise — trades only deep momentum shifts.",
            "Near-zero false signals in normal chop (it simply doesn't fire).",
            "A great study in what smoothing does to a signal.",
        ],
        "weaknesses": [
            "Very late: entries can be far from the actual turn.",
            "60-candle warm-up and heavy smoothing = slow account.",
            "Triple EMA parameters are abstract — hard to reason about intuitively.",
        ],
        "when": ["Long persistent trends.", "Useless (but harmless — it stays flat) in chop."],
        "mistakes": [
            "Expecting scalper behaviour from the bot's slowest momentum account.",
            "Tuning period to 5 'for speed' — that defeats the triple-smoothing design.",
            "Confusing TRIX units (% per candle of a smoothed line) with price %.",
        ],
        "watch": ["Trades will be rare — that's correct behaviour.", "Compare its entry quality vs strategy 02's on the same trends."],
        "concepts": ["trix", "ema", "momentum", "trend"],
        "related": ["03_macd_histogram_reversal", "02_dual_ema_crossover", "04_triple_moving_average"],
    },
    "20_ema_ribbon_consensus": {
        "difficulty": 2,
        "summary": "Five EMAs must agree: buy only the fully stacked bullish fan, sell only the fully stacked bearish one.",
        "idea": "The ribbon (8/13/21/34/55) shows trend at five speeds. When every line is ordered fast-to-slow from top to bottom, ALL timeframes agree — that's not a signal, that's a consensus. Tangled ribbons mean disagreement, and disagreement isn't tradeable.",
        "how": [
            "Compute EMAs for 8, 13, 21, 34 and 55.",
            "Fully ascending stack (8 > 13 > 21 > 34 > 55): buy.",
            "Hold while the stack stays ordered (even briefly tangled? no — rule is exact).",
            "Fully descending stack: sell.",
            "Anything between (tangled): hold whatever you have, enter nothing.",
        ],
        "params": {
            "periods": {"what": "Comma-separated EMA lengths forming the ribbon.", "effect": "More/faster EMAs = more sensitive; classic Fibonacci-ish spacing 8..55 balances speeds."},
        },
        "strengths": [
            "The unanimity requirement produces very high-quality trend entries.",
            "Transparent state: you can literally see the stack order each tick.",
            "Naturally sits out tangled markets.",
        ],
        "weaknesses": [
            "Slow: needs all five aligned, which happens late in trends.",
            "One recalcitrant EMA (e.g. 55 lagging) blocks entries for a long time.",
            "In strong trends it can exit on a single small bearish alignment then re-enter — chunky trades.",
        ],
        "when": ["Textbook trends with orderly pullbacks.", "Messy two-steps-forward-one-back markets keep it tangled (it waits, correctly)."],
        "mistakes": [
            "Reading 'most EMAs stacked' as the signal — the rule demands ALL five ordered.",
            "Expecting entries near bottoms; unanimity arrives after confirmation.",
            "Not noticing the exit is also a full alignment — half-hearted down moves don't exit it.",
        ],
        "watch": ["State can show the five values — check ordering on trade days.", "Ribbon tangles during pullbacks; that's normal and not an exit by itself."],
        "concepts": ["ema_ribbon", "ema", "trend", "consensus"],
        "related": ["04_triple_moving_average", "02_dual_ema_crossover", "39_multi_indicator_consensus"],
    },
}
