"""Lesson content, strategies 21-42. Merged with the strategy catalog by
scripts/generate_learn_assets.py."""

LESSONS_B = {
    # ------------------------------------------------------------------ #
    # Mean Reversion & Oscillators
    # ------------------------------------------------------------------ #
    "21_williams_r_reversal": {
        "difficulty": 1,
        "summary": "Where the close sits in the recent range, traded on the TURN: buy %R turning up from below −80, sell it reaching −20.",
        "idea": "Williams %R is the range position of the close, from 0 (top) to −100 (bottom). Below −80 price closed near the range floor — stretched. This strategy waits for the recovery turn out of the zone instead of buying while still falling.",
        "how": [
            "Compute %R(14): close's position in the 14-candle high-low range.",
            "%R below −80 then turns back above −80: buy (the dip is being bought).",
            "Hold while %R recovers.",
            "%R reaches −20 (overbought): sell.",
        ],
        "params": {
            "period": {"what": "Lookback for the high/low range.", "effect": "Shorter = tighter definition of 'recent range'."},
            "oversold": {"what": "The deep zone whose escape triggers the buy.", "effect": "More negative = only more extreme dips qualify."},
            "overbought": {"what": "The zone that ends the trade.", "effect": "Less negative (−10) = sells nearer the top; −20 standard."},
        },
        "strengths": [
            "Buys turns, not falls — avoids most falling knives.",
            "One scale (−100..0) makes state easy to read.",
            "Ranges cleanly with RSI (they usually agree at extremes).",
        ],
        "weaknesses": [
            "In a crash, %R stays pinned below −80 and the turn never comes.",
            "No trend context — will buy dips inside downtrends.",
            "The −20 exit is early in strong rallies.",
        ],
        "when": ["Range markets with sharp but recoverable dips.", "Strong trends defeat it both directions."],
        "mistakes": [
            "Buying the level (−85) instead of the turn (−85 → −79). The code requires the cross.",
            "Confusing %R direction conventions (some charting tools invert it).",
            "Forgetting it's close-position only — wicks don't matter.",
        ],
        "watch": ["State prints %R; entries should follow candles that undercut then reclaim.", "Flat account during straight-down crashes = the turn never fired."],
        "concepts": ["williams_r", "mean_reversion", "oscillator", "support_resistance"],
        "related": ["01_rsi_mean_reversion", "08_stoch_rsi_reversal", "22_cci_mean_reversion"],
    },
    "22_cci_mean_reversion": {
        "difficulty": 2,
        "summary": "Statistical stretch, commodity style: CCI below −100 turning up = buy; above +100 turning down = sell.",
        "idea": "CCI measures how far the typical price sits from its own average in noise units. Beyond ±100 is unusual — a move that big usually overshoots. This account fades the overshoot, entering on the return through the ±100 lines.",
        "how": [
            "Compute CCI(20) from typical price (H+L+C)/3.",
            "CCI crosses UP through −100: buy (the panic is unwinding).",
            "Hold while CCI climbs.",
            "CCI crosses DOWN through +100: sell (the euphoria is unwinding).",
        ],
        "params": {
            "period": {"what": "Lookback for CCI's average and deviation.", "effect": "Larger = smoother CCI, later crosses."},
            "lower": {"what": "The oversold line whose up-cross buys.", "effect": "More negative = rarer, more extreme entries."},
            "upper": {"what": "The overbought line whose down-cross sells.", "effect": "Lower (e.g. 80) = earlier exits; standard ±100."},
        },
        "strengths": [
            "Built-in noise scaling: reacts to moves unusual for THIS market.",
            "Turns (crosses) rather than levels = better timing.",
            "Works on any instrument despite the 'commodity' name.",
        ],
        "weaknesses": [
            "Can sit beyond ±100 for a long time in trends (the cross never comes; you just wait).",
            "Typical-price averaging hides close behaviour.",
            "No volume component.",
        ],
        "when": ["Volatile ranges where overshoots revert.", "Strong trends keep CCI pinned — account idles."],
        "mistakes": [
            "Using CCI as a momentum-chaser; it's a reversion tool here.",
            "Misreading −100 as the buy point — the buy is the UP-CROSS of it.",
            "Forgetting 0.015 is baked in: ±100 is a statistical convention, not magic.",
        ],
        "watch": ["State shows CCI; entries happen right after deep dips, not at them.", "Long flat stretches are the strategy correctly refusing weak setups."],
        "concepts": ["cci", "mean_reversion", "oscillator", "volatility"],
        "related": ["26_chande_momentum", "21_williams_r_reversal", "01_rsi_mean_reversion"],
    },
    "23_connors_rsi_pullback": {
        "difficulty": 3,
        "summary": "Three oversold lenses at once: fast RSI + down-streak length + 100-day rank, blended below 10 = a serious short-term dip.",
        "idea": "One oversold reading can be noise; three agreeing oversold readings are a stretched rubber band. CRSI averages RSI(3), a 'streak' RSI (how many red candles in a row) and the close's percentile rank over 100 candles. Below 10 is extreme by any lens — the pullback this account buys.",
        "how": [
            "Compute CRSI = (RSI(3) + streak-RSI(2) + rank(100))/3.",
            "CRSI ≤ 10: buy — a real short-term flush.",
            "Hold while it recovers.",
            "CRSI ≥ 90: sell the snap-back.",
        ],
        "params": {
            "rsi_period": {"what": "Fast RSI length.", "effect": "3 is Connors' standard for short-term stretch."},
            "streak_period": {"what": "Window for the consecutive-red-candle RSI.", "effect": "Captures how long the fall has run."},
            "rank_period": {"what": "Lookback for the close's percentile rank.", "effect": "Longer = stricter 'rare' filter."},
            "buy_below": {"what": "Entry threshold.", "effect": "Lower = rarer, deeper pullbacks only."},
            "sell_above": {"what": "Exit threshold.", "effect": "Higher = holds for a fuller recovery."},
        },
        "strengths": [
            "Designed specifically for buying pullbacks that statistically bounce.",
            "The streak component captures 'down too many days in a row'.",
            "Research-backed (Connors) with sensible defaults.",
        ],
        "weaknesses": [
            "110-candle warm-up — slow start.",
            "In a real bear, consecutive red streaks keep CRSI low and it keeps buying.",
            "Aggressive: buys after multi-day drops without a trend filter.",
        ],
        "when": ["Sharp 3-7 candle drops inside calmer markets.", "Brutal in sustained bear phases."],
        "mistakes": [
            "Thinking RSI(2)-style signals predict bottoms — they measure stretch.",
            "Not respecting that each extra red day makes the NEXT buy bigger in a falling market.",
            "Judging it during warm-up (first ~110 candles it cannot trade).",
        ],
        "watch": ["Entries should cluster after visible red streaks.", "If it's flat during huge red candles, check warm-up and CRSI level in state."],
        "concepts": ["connors_rsi", "rsi", "mean_reversion", "pullback", "streak"],
        "related": ["01_rsi_mean_reversion", "40_trend_pullback_confluence", "24_zscore_mean_reversion"],
    },
    "24_zscore_mean_reversion": {
        "difficulty": 2,
        "summary": "The statistical trade: buy price 2 standard deviations below its own average, sell when it returns to the average.",
        "idea": "A z-score converts price distance into statistical units: −2 means a move this large happens only a few percent of the time. Either something fundamental changed (don't buy) or price is stretched (buy). This account bets on stretch, and defines 'back to normal' as z = 0 — no greedy targets.",
        "how": [
            "Compute z = (close − SMA20)/stdev20 each candle.",
            "z ≤ −2: buy — price statistically stretched downward.",
            "Hold while price is below its mean.",
            "z ≥ 0: sell — reversion to the average is complete.",
        ],
        "params": {
            "period": {"what": "Lookback for mean and standard deviation.", "effect": "Longer = a more stable 'normal', slower to stretch."},
            "entry_z": {"what": "Stretch required to buy.", "effect": "More negative = only extreme dislocations traded."},
            "exit_z": {"what": "Where reversion is declared done.", "effect": "0 = sell at the mean; negative = sell early; positive = let it overshoot up."},
        },
        "strengths": [
            "Statistically principled: the entry has a real probability story.",
            "Objective, parameter-light, easy to explain.",
            "Exits at the mean — a humble, consistent target.",
        ],
        "weaknesses": [
            "Assumes mean reversion — false in genuine trend changes.",
            "Standard deviation on 20 candles is noisy itself.",
            "No fundamental or news filter; a halving or hack can make −2 the start, not the bottom.",
        ],
        "when": ["Mean-reverting conditions (normal chop, no regime news).", "Long trends stretch the z-score for weeks."],
        "mistakes": [
            "Assuming 'statistically rare' means 'financially safe'.",
            "Exiting at positive z to chase — the rule is zero.",
            "Ignoring that a flat market (tiny stdev) produces wild z-scores from small moves.",
        ],
        "watch": ["State prints z; it should be deeply negative around entries.", "Watch stdev context on the Market screen — small ranges inflate z."],
        "concepts": ["zscore", "mean_reversion", "oscillator", "volatility"],
        "related": ["01_rsi_mean_reversion", "06_bollinger_mean_reversion", "25_mfi_flow_reversal"],
    },
    "25_mfi_flow_reversal": {
        "difficulty": 1,
        "summary": "RSI with volume honesty: MFI ≤ 20 means selling pressure is exhausted; buy it, sell the ≥ 80 euphoria.",
        "idea": "Prices move on volume. MFI weights every candle by how much was traded, so a drop to 20 means heavy selling has dominated — and heavy selling that can't push further is what bottoms look like. It's the money-weighted twin of RSI.",
        "how": [
            "Compute MFI(14) using typical price × volume.",
            "MFI ≤ 20: buy (volume-backed oversold).",
            "Hold while pressure normalizes.",
            "MFI ≥ 80: sell (volume-backed overbought).",
        ],
        "params": {
            "period": {"what": "Lookback for money flow.", "effect": "14 standard; shorter = noisier, more sensitive."},
            "oversold": {"what": "Entry threshold.", "effect": "Lower = only capitulation-grade selling bought."},
            "overbought": {"what": "Exit threshold.", "effect": "Lower = exits earlier with less giveback."},
        },
        "strengths": [
            "Volume-aware: cheap moves driven by thin volume don't trigger it.",
            "Simple 0-100 scale like RSI.",
            "Capitulation readings (≤20) historically mark decent bounces in BTC.",
        ],
        "weaknesses": [
            "Still a level-based fade — no trend filter.",
            "Volume prints on Kraken can be lumpy (aggregated venues).",
            "Divergences (price low but MFI higher) are ignored by the simple thresholds.",
        ],
        "when": ["Volume-backed sell-offs that stall.", "Trending markets: MFI pins at extremes and thresholds misfire."],
        "mistakes": [
            "Reading MFI 20 like RSI 30 — thresholds aren't interchangeable.",
            "Ignoring that volume extremes at news events are different from drift.",
            "Forgetting warm-up: MFI needs full windows of both price and volume.",
        ],
        "watch": ["Entries should coincide with high-volume red candles on the Market screen.", "State prints MFI — check it bottomed before entries."],
        "concepts": ["mfi", "volume", "mean_reversion", "oscillator"],
        "related": ["01_rsi_mean_reversion", "28_volume_spike_breakout", "27_obv_trend_breakout"],
    },
    "26_chande_momentum": {
        "difficulty": 2,
        "summary": "Symmetric momentum flow: buy the turn up through −50, sell the turn down through +50.",
        "idea": "CMO divides net up-move size by total movement, giving a bounded ±100 flow meter where 50 means 'half the recent energy was directional'. Crossing −50 upward is the exhaustion of a heavy down-flow — the same fade-the-extreme idea as CCI, with cleaner math.",
        "how": [
            "Compute CMO(20) from up/down move sums.",
            "CMO crosses UP through −50: buy.",
            "Hold while up-flow dominates.",
            "CMO crosses DOWN through +50: sell.",
        ],
        "params": {
            "period": {"what": "Lookback for summing moves.", "effect": "Longer = smoother flow readings."},
            "entry": {"what": "Down-flow line whose up-cross buys.", "effect": "More negative = only deeper flow exhaustion."},
            "exit": {"what": "Up-flow line whose down-cross sells.", "effect": "Lower = earlier exits."},
        },
        "strengths": [
            "Symmetric, bounded, and volume-free but still robust.",
            "Turn-based entries time dips better than level-based ones.",
            "Less crowd-followed than RSI — fewer self-fulfilling signals.",
        ],
        "weaknesses": [
            "Obscure — harder to find reference material.",
            "No trend filter, same falling-knife risk as all fades.",
            "±50 thresholds are convention, not statistics.",
        ],
        "when": ["Two-sided markets with real up/down flow alternation.", "One-way flows keep CMO pinned and cross-less."],
        "mistakes": [
            "Using CMO like ROC (momentum-chasing) — here it's a reversion turn signal.",
            "Reading −50 as the level vs the turn through it.",
            "Overriding exits because the position is green — the flow rule owns the decision.",
        ],
        "watch": ["Entries should come after extended red runs, on the first strong green candle.", "State prints CMO values around trades."],
        "concepts": ["cmo", "momentum", "mean_reversion", "oscillator"],
        "related": ["22_cci_mean_reversion", "21_williams_r_reversal", "25_mfi_flow_reversal"],
    },
    # ------------------------------------------------------------------ #
    # Volume & Volatility
    # ------------------------------------------------------------------ #
    "09_vwap_pullback": {
        "difficulty": 2,
        "summary": "Institutional fair value: buy dips below the session VWAP while RSI is still healthy; sell 1.5% extensions above it.",
        "idea": "VWAP is the volume-weighted average price of the session — where big money's average cost sits. Price below VWAP is 'cheap' intraday. This account buys cheap dips that aren't broken (RSI > 40 — the dip is a pullback, not a collapse) and sells when price stretches 1.5% above VWAP.",
        "how": [
            "Rebuild VWAP each UTC session from candle typical prices × volume.",
            "Require the session to be old enough (≥2 candles).",
            "Close < VWAP and RSI(14) > 40: buy — dip without damage.",
            "Close ≥ VWAP × 1.015: sell — extension complete.",
        ],
        "params": {
            "rsi_period": {"what": "RSI lookback for the health filter.", "effect": "14 standard."},
            "rsi_min": {"what": "Minimum RSI to allow buying a dip.", "effect": "Higher = only mild dips bought (safer, less often)."},
            "extension_pct": {"what": "How far above VWAP triggers the exit.", "effect": "Smaller = tighter profit taking."},
            "min_session_candles": {"what": "Session age before trading.", "effect": "Higher = waits for a more established VWAP."},
        },
        "strengths": [
            "Trades against a genuinely meaningful anchor (real traded value).",
            "The RSI>40 filter avoids catching broken dips.",
            "Sessions give the strategy a natural daily rhythm.",
        ],
        "weaknesses": [
            "Assumes VWAP acts as gravity — false on strong trend days.",
            "RSI 40 as 'healthy' is arbitrary.",
            "Nothing stops it buying repeatedly into a falling session.",
        ],
        "when": ["Normal two-sided sessions.", "Trend days: price may never dip under VWAP (no entries) or never return (held losses)."],
        "mistakes": [
            "Expecting VWAP support to hold on news days — it often doesn't.",
            "Forgetting sessions reset: VWAP is per-day, not a 50-candle average.",
            "Ignoring the RSI filter — it's the difference between pullback and collapse.",
        ],
        "watch": ["State stores VWAP — compare against price on the Market screen.", "Entries cluster in the early session hours (right after range forms)."],
        "concepts": ["vwap", "pullback", "volume", "rsi"],
        "related": ["40_trend_pullback_confluence", "01_rsi_mean_reversion", "34_opening_range_breakout"],
    },
    "10_donchian_breakout": {
        "difficulty": 2,
        "summary": "The Turtle's classic: buy closes above the 20-candle high, exit closes below the 10-candle low.",
        "idea": "The Turtle Traders made fortunes with one idea: markets that break their recent range keep going. A close above the highest high of 20 candles is a real structural break (strictly prior candles — no self-reference). The 10-candle low exit cuts losers before they grow.",
        "how": [
            "Track Donchian channel: 20-candle high (entry), 10-candle low (exit).",
            "Close breaks above the 20-candle high: buy.",
            "Hold while price stays above the 10-candle low.",
            "Close breaks below the 10-candle low: sell.",
            "Trend-following in its purest, oldest form.",
        ],
        "params": {
            "entry_period": {"what": "Window for the breakout high.", "effect": "Longer = bigger, rarer breakouts (later entries)."},
            "exit_period": {"what": "Window for the exit low.", "effect": "Shorter = exits sooner, smaller losses and givebacks."},
        },
        "strengths": [
            "Objective, famous, and brutally effective in trends.",
            "No averaging or smoothing to second-guess.",
            "Exits cut losses quickly (10-candle low is close to price).",
        ],
        "weaknesses": [
            "Whipsaws in ranges: every range-top close is a false breakout.",
            "Buys at visible highs — psychologically hard.",
            "No volatility or volume confirmation.",
        ],
        "when": ["Explosive directional phases.", "Ranges and descending channels punish it."],
        "mistakes": [
            "Using intra-candle breaks — the rule is a CLOSE beyond the level.",
            "Widening the exit to 'give winners room' — that's a different strategy.",
            "Expecting it to catch exact bottoms; it buys strength, by design.",
        ],
        "watch": ["Entries should be visible on the Market screen as closes above prior highs.", "Trade bursts cluster at the start of trends — compare with strategy 28 (volume-confirmed)."],
        "concepts": ["donchian", "breakout", "trend", "support_resistance"],
        "related": ["28_volume_spike_breakout", "37_anti_martingale_pyramid", "38_kelly_fraction_sizer"],
    },
    "27_obv_trend_breakout": {
        "difficulty": 2,
        "summary": "The lie-detector breakout: buy only when OBV AND price both break their 20-candle highs together.",
        "idea": "Price can break a level on a whisper; OBV can't lie — it accumulates every up/down candle's volume. When OBV makes a new 20-candle high and price confirms with its own new high, the breakout is backed by real flow. That's the breakout worth joining.",
        "how": [
            "Build OBV: add volume on up closes, subtract on down closes.",
            "Require OBV above its prior 20-candle range AND",
            "Close above the prior 20-candle high: buy (double confirmation).",
            "Hold while flow stays constructive.",
            "OBV breaks its 20-candle LOW: sell (distribution detected).",
        ],
        "params": {
            "lookback": {"what": "Window for OBV and price extremes.", "effect": "Longer = larger-scale flow breaks."},
        },
        "strengths": [
            "Requires price AND flow to agree — filters many fakeouts.",
            "The OBV-low exit catches quiet distribution before price collapses.",
            "Rising OBV is visible on charts for intuitive confirmation.",
        ],
        "weaknesses": [
            "OBV levels depend on the whole account history — scale is arbitrary.",
            "In strongly trending markets OBV never makes 'new lows', delaying exits.",
            "Two confirmations from related quantities still share one worldview.",
        ],
        "when": ["Breakouts with genuine participation.", "Low-volume drift markets never satisfy the flow test (correctly)."],
        "mistakes": [
            "Reading OBV's absolute level — only its breaks matter.",
            "Trading price breakouts without the OBV confirmation (that's strategy 10's job).",
            "Forgetting OBV's starting point distorts nothing but its scale.",
        ],
        "watch": ["Entries should show elevated volume bars on the Market screen.", "Exits should precede big red candles if distribution is real."],
        "concepts": ["obv", "volume", "breakout", "trend"],
        "related": ["28_volume_spike_breakout", "10_donchian_breakout", "25_mfi_flow_reversal"],
    },
    "28_volume_spike_breakout": {
        "difficulty": 1,
        "summary": "The loud breakout: 2× normal volume AND a close above the 20-candle high — real money, real break.",
        "idea": "Silent breakouts are suspect; loud ones are real. When a candle trades at double the average volume and still closes above the 20-candle high, institutions participated and won. This account joins loud breaks and exits when price closes under the 10-candle low.",
        "how": [
            "Compute average volume over the prior 20 candles.",
            "Latest volume ≥ 2× average AND close > prior 20-candle high: buy.",
            "Hold while the breakout holds.",
            "Close breaks below the 10-candle low: sell.",
        ],
        "params": {
            "lookback": {"what": "Window for volume average and the high.", "effect": "Longer = more established norms to beat."},
            "volume_mult": {"what": "Spike size required.", "effect": "Higher = only exceptional participation traded."},
            "exit_lookback": {"what": "Window for the exit low.", "effect": "Shorter = tighter exits."},
        },
        "strengths": [
            "Volume confirmation dramatically improves breakout quality.",
            "Simple, visual, and easy to verify on the Market screen.",
            "Catches exactly the moves that trend systems profit from.",
        ],
        "weaknesses": [
            "Volume spikes at news can be one-candle wonders (fakeouts).",
            "Requires waiting through quiet markets with no signals.",
            "No consideration of WHERE the breakout happens (range top vs mid-air).",
        ],
        "when": ["High-conviction directional candles after compression.", "Quiet drift produces no entries — and that's fine."],
        "mistakes": [
            "Lowering volume_mult to 1.2 'to trade more' — you're rebuilding strategy 10 with extra steps.",
            "Ignoring that spike + close are both required, not either.",
            "Confusing Kraken volume units across pairs.",
        ],
        "watch": ["Every entry should have a visible volume bar ≥ 2× neighbours on the Market screen.", "Compare trade quality with strategy 10 (no volume filter)."],
        "concepts": ["volume_spike", "volume", "breakout", "liquidity"],
        "related": ["10_donchian_breakout", "27_obv_trend_breakout", "16_roc_momentum"],
    },
    "29_volatility_squeeze": {
        "difficulty": 3,
        "summary": "The coiled spring: when Bollinger bands compress inside Keltner, volatility is loading — buy the release above the middle band.",
        "idea": "Markets alternate between compression and expansion. When Bollinger (stdev-based) bands squeeze inside Keltner (ATR-based) bands, volatility has died down to statistical extremes — energy is building. When the bands finally fire apart, the bot joins if the release candle closes above the middle band.",
        "how": [
            "Compute Bollinger(20, 2) and Keltner(20, 1.5) bands.",
            "Detect squeeze: Bollinger bands fully inside Keltner bands.",
            "Wait for the release: bands expand again (squeeze off).",
            "Release candle closes above the Bollinger middle: buy.",
            "Exit when close falls back below the middle band.",
        ],
        "params": {
            "bb_period": {"what": "Bollinger lookback.", "effect": "Standard 20."},
            "bb_mult": {"what": "Bollinger width in stdevs.", "effect": "2 standard."},
            "kc_period": {"what": "Keltner EMA lookback.", "effect": "Standard 20."},
            "kc_mult": {"what": "Keltner width in ATRs.", "effect": "1.5 makes the squeeze test meaningful against 2-stdev Bollinger."},
        },
        "strengths": [
            "Trades the highest-conviction moments in technical analysis.",
            "Explicit compression state, explicit release trigger.",
            "Squeezes are objectively measurable — no eyeballing.",
        ],
        "weaknesses": [
            "Squeezes can 'fire' repeatedly without a real move (false releases).",
            "Long idle periods while compressed.",
            "Four coupled parameters to reason about.",
        ],
        "when": ["Calm consolidation followed by expansion — textbook spring setups.", "Continuous trending or continuous chop both suppress signals."],
        "mistakes": [
            "Buying the squeeze itself — the signal is the RELEASE.",
            "Assuming direction; the close-vs-middle-band test is what picks the side.",
            "Forgetting both band pairs must be compared on the same candle.",
        ],
        "watch": ["State shows squeeze state; look at the Market screen for tight Bollinger-in-Keltner windows.", "Entries should appear right after visible compression phases end."],
        "concepts": ["volatility_squeeze", "bollinger", "keltner", "volatility", "breakout"],
        "related": ["41_volatility_regime_switcher", "10_donchian_breakout", "06_bollinger_mean_reversion"],
    },
    "30_elder_ray_power": {
        "difficulty": 2,
        "summary": "Tug-of-war with rulers: buy when bear power fails (crosses back above zero) while bulls stay positive; sell when bull power rolls over.",
        "idea": "Elder-Ray measures how far buyers (high − EMA13) and sellers (low − EMA13) can push from the crowd's center. A rally dies when bear power — how deep sellers reached — stops making new lows and lifts through zero. That's the exact moment to buy: sellers just lost the rope.",
        "how": [
            "Compute bull power = high − EMA(13), bear power = low − EMA(13).",
            "Bear power ≤ 0 last candle, then > 0 now, with bull power positive: buy.",
            "Hold while buyers keep reach.",
            "Bull power falls below zero (sellers control the EMA line): sell.",
        ],
        "params": {
            "period": {"what": "EMA length both powers use.", "effect": "13 is Elder's standard; longer = slower regime shifts."},
        },
        "strengths": [
            "Measures force, not just price — who pushed further.",
            "The bear-power-reclaim entry is a genuine capitulation detector.",
            "Symmetric long/short logic is elegant to study.",
        ],
        "weaknesses": [
            "EMA(13) as 'fair value' is arbitrary.",
            "Intraday wicks dominate the highs/lows used in the math.",
            "In slow grinds powers hover near zero and signals turn mushy.",
        ],
        "when": ["Volatile two-sided markets with real thrusts.", "Dead quiet drift gives ambiguous near-zero readings."],
        "mistakes": [
            "Reading bull power alone — the entry needs the BEAR power failure.",
            "Forgetting power is measured in dollars from the EMA, not a percentage.",
            "Judging it on tiny candles where a one-dollar wick flips the sign.",
        ],
        "watch": ["State stores bull/bear power — entries follow negative-then-positive bear power.", "Power magnitudes shrink in quiet sessions (smaller dollar reach)."],
        "concepts": ["elder_ray", "volume", "oscillator", "volatility"],
        "related": ["25_mfi_flow_reversal", "01_rsi_mean_reversion", "29_volatility_squeeze"],
    },
    # ------------------------------------------------------------------ #
    # Price Action
    # ------------------------------------------------------------------ #
    "31_engulfing_reversal": {
        "difficulty": 2,
        "summary": "The candle that swallows its predecessor: bullish engulfing at the end of a 10-candle downtrend = buy; the mirror = sell.",
        "idea": "A green body that fully covers the previous red body is one candle saying 'all of yesterday's sellers are trapped'. Alone it's noise — after a measured 10-candle downtrend it's a reversal with a crowd behind it. Context is the whole trade.",
        "how": [
            "Confirm a real downtrend: close 10 candles ago ≥ 1% above the prior close.",
            "Look at the last two candles: bullish engulfing (green body fully wraps red body)?",
            "Yes: buy. The downtrend just got rejected by a bigger counter-candle.",
            "Exit when an uptrend of similar size produces a bearish engulfing.",
        ],
        "params": {
            "trend_lookback": {"what": "Candles used to measure the prior trend.", "effect": "Longer = requires deeper trends before acting."},
            "trend_pct": {"what": "Minimum prior move to count as a trend.", "effect": "Higher = only significant trends traded."},
        },
        "strengths": [
            "The trend filter turns a common pattern into a context-aware signal.",
            "Candle logic is visual and verifiable by eye.",
            "Fast reaction: reversal detected within one candle.",
        ],
        "weaknesses": [
            "Engulfing bars in 15m crypto are frequent — many are noise despite the filter.",
            "No volume confirmation of the engulfing candle.",
            "One-candle exits can be shaken out before real reversals develop.",
        ],
        "when": ["Trend exhaustion zones after clear directional runs.", "Chop produces engulfings everywhere (filtered poorly by short trends)."],
        "mistakes": [
            "Trading engulfings without trend context (the pattern alone is a coin flip).",
            "Measuring bodies instead of the full-candle rule (body must fully wrap prior BODY).",
            "Expecting instant follow-through; reversals often retest first.",
        ],
        "watch": ["Entries should visually match big green candles swallowing red ones at local lows.", "False signals concentrate in ranges — compare with trend filters (40)."],
        "concepts": ["engulfing", "candlestick", "support_resistance", "pullback"],
        "related": ["40_trend_pullback_confluence", "33_pivot_point_bounce", "32_fibonacci_pullback"],
    },
    "32_fibonacci_pullback": {
        "difficulty": 2,
        "summary": "The golden dip: in an uptrend, buy the pullback when it reaches the 0.618 retracement of the prior swing; sell the recovery to 0.236.",
        "idea": "After a swing up, pullbacks often die at Fibonacci levels — 0.618 most of all, because half the market watches it. Strategy 32 waits for an uptrend, lets the dip come all the way into the deep 0.618 zone, and buys when price crosses back above it.",
        "how": [
            "Find the last 50-candle swing: its high and low.",
            "Confirm uptrend: close now > close 50 candles ago.",
            "Price dips to the 0.618 retracement then closes back above it: buy.",
            "Ride the recovery.",
            "Close reaches the 0.236 retracement (shallow zone near the old high): sell.",
        ],
        "params": {
            "swing_lookback": {"what": "Window defining the swing high/low.", "effect": "Longer = bigger structural swings."},
            "entry_level": {"what": "Retracement depth that is 'the dip'.", "effect": "0.618 is deep; 0.382 buys shallower dips more often."},
            "exit_level": {"what": "Recovery level that ends the trade.", "effect": "0.236 exits near the highs; higher values exit earlier."},
        },
        "strengths": [
            "Structural levels (not noise averages) define the trade.",
            "Deep-entry + early-exit asymmetry is attractive.",
            "Self-fulfilling to a degree — Fibonacci is widely watched.",
        ],
        "weaknesses": [
            "Swing highs/lows from 50 candles can be stale in fast markets.",
            "Pullbacks can blow THROUGH 0.618 into full reversals — no stop here.",
            "Level choice (0.618 vs 0.5) is convention, not law.",
        ],
        "when": ["Orderly uptrends with measured pullbacks.", "Vertical moves rarely retrace politely; crashes blow through all levels."],
        "mistakes": [
            "Buying the level before the reclaim-close — the code buys the cross back above.",
            "Expecting every 0.618 to hold; it's a probability, not a promise.",
            "Forgetting the uptrend gate: no trend, no trade.",
        ],
        "watch": ["Entries should be visible as dips to ~0.618 of a clear swing on the chart.", "Compare with strategy 40 — same idea, different measurement tools."],
        "concepts": ["fibonacci", "pullback", "support_resistance", "trend"],
        "related": ["40_trend_pullback_confluence", "33_pivot_point_bounce", "01_rsi_mean_reversion"],
    },
    "33_pivot_point_bounce": {
        "difficulty": 2,
        "summary": "Yesterday's levels, today's map: buy S1 support being reclaimed, sell into R1 resistance.",
        "idea": "Pivot points derive today's support/resistance from yesterday's high, low and close. They're arithmetic, public, and shared by thousands of traders — which makes them work. This account buys when S1 (first support) is tested and reclaimed, and sells into R1 (first resistance).",
        "how": [
            "Each new UTC session: compute P, S1, R1 from the prior session's HLC.",
            "Prior close at/below S1 and current close back above S1: buy (floor defended).",
            "Ride toward the pivot.",
            "Close reaches R1: sell into the ceiling.",
        ],
        "params": {
            "alloc": {"what": "Cash share per entry.", "effect": "None = the global 95% default applies."},
        },
        "strengths": [
            "Levels are objective and shared — crowd gravity works for you.",
            "Fresh levels every session keep it anchored to current prices.",
            "Very low warm-up (5 candles).",
        ],
        "weaknesses": [
            "Levels ignore news: a gap through S1 makes the 'reclaim' pattern moot.",
            "Range-bound by construction — trend days run through R1 and keep going.",
            "No stop: a broken S1 that keeps falling just holds the position.",
        ],
        "when": ["Two-sided sessions respecting yesterday's map.", "Trend days and gap sessions invalidate the levels quickly."],
        "mistakes": [
            "Buying S1 touches instead of reclaim closes.",
            "Using daily pivots on 15m candles — sessions must match (UTC here).",
            "Treating S1 as a hard floor; it's a defended-but-breakable line.",
        ],
        "watch": ["State prints the pivot table — compare price against S1/R1 each session.", "Entries should cluster right after undercut-and-reclaim wicks at S1."],
        "concepts": ["pivot_points", "support_resistance", "mean_reversion", "trend"],
        "related": ["34_opening_range_breakout", "06_bollinger_mean_reversion", "31_engulfing_reversal"],
    },
    "34_opening_range_breakout": {
        "difficulty": 1,
        "summary": "First hour sets the tone: buy the first close above the UTC opening range high, exit below its low.",
        "idea": "The opening range (first 60 minutes) captures where the overnight crowd is willing to trade. Whoever breaks it first usually controls the day. This account is a morning observer: it waits for the hour to complete, then trades the first decisive close beyond the range.",
        "how": [
            "Each UTC session, measure the opening range: high/low of the first 60 minutes.",
            "Wait until the range is complete (4+ candles in).",
            "First close ABOVE the range high: buy — early strength confirmed.",
            "Close back BELOW the range low: sell — the thesis failed.",
        ],
        "params": {
            "minutes": {"what": "Length of the opening range.", "effect": "Longer = more established range, later signals; 60 is the classic."},
        },
        "strengths": [
            "Simple, time-boxed, and psychologically grounded.",
            "Only trades once per session at most — disciplined.",
            "Clear invalidation (range-low break) keeps losses defined.",
        ],
        "weaknesses": [
            "One trade window per day — misses afternoon moves entirely.",
            "Fake range breaks are common in crypto's 24/7 sessions.",
            "UTC 'open' is arbitrary for a market that never closes.",
        ],
        "when": ["Sessions with genuine early direction.", "Listless sessions produce range-poke fakeouts both ways."],
        "mistakes": [
            "Trading inside the opening hour — the range is still forming.",
            "Entering on wicks through the high instead of closes.",
            "Expecting it to work outside the session structure it was designed for.",
        ],
        "watch": ["Entries happen only shortly after each UTC hour-mark.", "Check state for the stored range high/low on trade days."],
        "concepts": ["opening_range", "breakout", "support_resistance", "trend"],
        "related": ["09_vwap_pullback", "33_pivot_point_bounce", "10_donchian_breakout"],
    },
    # ------------------------------------------------------------------ #
    # Risk & Trailing
    # ------------------------------------------------------------------ #
    "35_chandelier_trend_ride": {
        "difficulty": 2,
        "summary": "Enter on trend confirmation, exit on a stop hung 3×ATR below the highest high since entry — volatility-scaled trend riding.",
        "idea": "Most trend exits are arbitrary percentages. The chandelier hangs its stop from the ceiling of the move (highest high since entry) minus 3×ATR, so the stop is exactly as wide as the market's current noise. If price falls more than three typical ranges from the peak, the trend is genuinely broken — not just breathing.",
        "how": [
            "Confirm uptrend: close crosses above EMA(50).",
            "Buy the cross.",
            "Track the chandelier stop = highest high since entry − 3×ATR(22).",
            "Hold while price stays above the stop.",
            "Close under the stop: sell — the ride is over.",
        ],
        "params": {
            "trend_period": {"what": "EMA length for trend confirmation.", "effect": "Longer = later entries, stronger trends only."},
            "atr_period": {"what": "ATR lookback sizing the stop.", "effect": "22 standard for daily-style stops."},
            "multiplier": {"what": "Stop distance in ATRs.", "effect": "Higher = wider stops, fewer shake-outs, more giveback."},
        },
        "strengths": [
            "Volatility-scaled exit — correct behaviour in both calm and stormy markets.",
            "Rides the full trend once in: no premature targets.",
            "The EMA entry gate keeps it out of counter-trend bounces.",
        ],
        "weaknesses": [
            "ATR(22) on 15m candles mixes overnight and daytime volatility.",
            "3×ATR giveback can be large on volatile BTC.",
            "EMA(50) confirmation means late entries near local tops sometimes.",
        ],
        "when": ["Sustained trends with expanding peaks.", "Chop: entries on weak crosses, exits on noise — small repeated losses."],
        "mistakes": [
            "Reading the stop as a target — it's a maximum giveback, not a profit level.",
            "Using daily ATR intuition on 15m candles.",
            "Tightening the multiplier after one bad trade (whipsaw feedback loop).",
        ],
        "watch": ["State stores chandelier_stop — it should climb with price during the ride.", "Exits should come on the first close that undercuts a multi-candle peak."],
        "concepts": ["chandelier_exit", "atr", "trailing_stop", "trend"],
        "related": ["05_supertrend_atr", "37_anti_martingale_pyramid", "04_triple_moving_average"],
    },
    # ------------------------------------------------------------------ #
    # Execution-Based & Portfolio
    # ------------------------------------------------------------------ #
    "11_dynamic_dca": {
        "difficulty": 1,
        "summary": "The disciplined accumulator: buys every hour, twice as much when the last 24h is red — no timing judgement, ever.",
        "idea": "Nobody can time BTC. DCA doesn't try: it buys a fixed amount hourly, and doubles the order when the trailing 24 hours are down — buying the dip harder but still on a schedule. It builds a ladder of lots and never panics; optional take-profit exits the whole stack at a gain.",
        "how": [
            "Every 4th candle (hourly): place a buy of the base notional.",
            "If the trailing 24h (96 candles) is negative: double the order.",
            "Skip if the order would exceed available cash.",
            "Accumulate lots indefinitely (multi-position account).",
            "Optional: if take_profit_pct is set, sell the whole stack when its average gain hits it.",
        ],
        "params": {
            "interval_candles": {"what": "Candles between scheduled buys.", "effect": "4 = hourly on 15m candles."},
            "base_notional": {"what": "Regular order size in USDT.", "effect": "Higher = faster accumulation, faster cash burn."},
            "dip_multiplier": {"what": "Order multiplier on red 24h windows.", "effect": "2 = double down on dips; higher is more aggressive."},
            "lookback_24h": {"what": "Candles defining 'recent' for the dip test.", "effect": "96 = 24 hours of 15m candles."},
            "take_profit_pct": {"what": "Optional whole-stack profit target.", "effect": "None = never sells, pure accumulator."},
        },
        "strengths": [
            "Removes timing emotion completely — the strategy is a schedule.",
            "Dip-doubling buys more when prices are cheaper.",
            "No market judgement to get wrong.",
        ],
        "weaknesses": [
            "In a long bear it keeps buying into falling prices (that's the plan — painful on paper).",
            "Cash is finite: dips stop being doubled once affordable cash runs out.",
            "Without a take-profit it can hold for years below average cost.",
        ],
        "when": ["Always (it's time-based). Best in volatile-but-eventually-up markets.", "Long secular bears stress it most."],
        "mistakes": [
            "Judging it by win rate — DCA is about average cost, not per-trade hits.",
            "Expecting it to sell rallies — by default it only buys.",
            "Forgetting the dip-double still respects the cash constraint.",
        ],
        "watch": ["Watch 'runs' in state — buys fire exactly every 4 ticks.", "The 24h change in state explains why some orders were doubled."],
        "concepts": ["dca", "lot", "position_sizing", "mean_reversion"],
        "related": ["36_martingale_dip", "12_arithmetic_grid", "38_kelly_fraction_sizer"],
    },
    "12_arithmetic_grid": {
        "difficulty": 2,
        "summary": "A machine that sells volatility: resting limit buys every 1% step down, each lot sold one step higher — round trips on autopilot.",
        "idea": "In a range, every dip is temporary. The grid places 5 buy orders below the current price and sells each filled lot exactly one step higher: a completed round trip banks the step profit (minus two fees). When price trends far away, the whole ladder re-anchors to the new location instead of holding dead inventory.",
        "how": [
            "Anchor a ladder at the current price: 5 buy levels below, mirror levels above.",
            "When price touches a buy level: fill it (limit order).",
            "When price rises one step above a filled level: sell it — round trip banked.",
            "If price drifts beyond the channel (6%): liquidate stale inventory and rebuild the ladder at the new price.",
            "Levels are sized from current equity, so the grid shrinks after losses and compounds after wins.",
        ],
        "params": {
            "step_pct": {"what": "Price spacing between levels.", "effect": "1% steps must beat ~0.2% round-trip fees — smaller steps get fee-eaten."},
            "levels_each_side": {"what": "Buy levels below the anchor.", "effect": "More = deeper range coverage, more capital spread thin."},
            "capital_pct": {"what": "Equity share committed to the ladder.", "effect": "Higher = bigger fills per level."},
            "reanchor_pct": {"what": "Drift that triggers a ladder rebuild.", "effect": "Smaller = adapts faster, sells inventory more often."},
        },
        "strengths": [
            "Mechanically harvests range volatility — hundreds of small wins.",
            "Re-anchoring keeps it alive through trends.",
            "Beautiful live state: watch the ladder fill and sell in real time.",
        ],
        "weaknesses": [
            "Each round trip nets ~0.8% after fees: trends give it no trips, only inventory.",
            "Re-anchors lock in losses by liquidating underwater lots.",
            "Range assumption can bleed slowly in one-way markets.",
        ],
        "when": ["Chop between levels (BTC's favourite pastime).", "Long one-way trends eat it via repeated re-anchor losses."],
        "mistakes": [
            "Setting steps below ~0.4% — fees eat the whole edge.",
            "Judging it on days without trips; grids earn in bursts.",
            "Misreading re-anchor sells as strategy failure — they're the designed escape hatch.",
        ],
        "watch": ["Live grid state: levels, round_trips, rebuilt count.", "Round trips should accumulate during sideways sessions."],
        "concepts": ["grid", "lot", "position_sizing", "fee", "slippage"],
        "related": ["11_dynamic_dca", "36_martingale_dip", "37_anti_martingale_pyramid"],
    },
    "36_martingale_dip": {
        "difficulty": 1,
        "summary": "The gambler's system, safety-capped: every 2% dip doubles the buy — up to 4 steps, and only while cash allows.",
        "idea": "Martingale logic: if you double each losing bet, one bounce recovers everything. Applied to dips: buy $100, price falls 2%, buy $200, falls again, buy $400... The cap (4 steps) and the cash check are what turn a blow-up machine into a (still spicy) system.",
        "how": [
            "Anchor to the running peak price.",
            "Price drops 2% from the anchor: buy the base notional.",
            "Each further 2% drop: double the order (100 → 200 → 400 → 800).",
            "Stop doubling at 4 steps or when the order exceeds available cash.",
            "Optional take-profit sells the whole stack at a gain; otherwise it holds forever.",
        ],
        "params": {
            "dip_pct": {"what": "Drop that triggers the next step.", "effect": "Smaller = more frequent escalation."},
            "base_notional": {"what": "First step size.", "effect": "Sets the whole ladder's scale."},
            "multiplier": {"what": "Step growth factor.", "effect": "2 doubles; higher escalates faster toward the cap."},
            "max_steps": {"what": "Hard cap on doublings.", "effect": "The cap IS the risk management — never remove it."},
            "take_profit_pct": {"what": "Optional whole-stack exit.", "effect": "None = hold through recovery (or forever)."},
        },
        "strengths": [
            "A single bounce fully recovers deep underwater positions.",
            "The step cap and cash constraint bound the worst case.",
            "Simple to understand and to watch.",
        ],
        "weaknesses": [
            "Escalation is exponential: steps 3-4 dwarf step 1 in size.",
            "In a sustained bear the cap forces it to stop buying exactly when things are cheapest.",
            "Fees apply to every doubling — the ladder leaks 0.2% per round trip.",
        ],
        "when": ["V-shaped dips in ranging markets.", "Slow grinding bears break its heart (and its average cost)."],
        "mistakes": [
            "Raising max_steps 'for better recovery' — that's how martingales destroy accounts.",
            "Judging it by unrealized losses mid-drawdown; the design is all-or-nothing-ish.",
            "Forgetting every doubling must clear fees too.",
        ],
        "watch": ["State shows steps and anchor_price — see the ladder build during dips.", "The account should recover in one move when price bounces past the anchor."],
        "concepts": ["martingale", "dca", "risk_management", "lot"],
        "related": ["11_dynamic_dca", "37_anti_martingale_pyramid", "12_arithmetic_grid"],
    },
    "37_anti_martingale_pyramid": {
        "difficulty": 2,
        "summary": "The winner's system: add a lot on every +2% leg of a winning breakout, protect everything with a 3% trail below the peak.",
        "idea": "If martingale doubles losers, anti-martingale adds to winners. Enter on a 20-candle high breakout, then each further 2% rise buys another leg (up to 3 adds, each 30% of starting balance). A 3% trail below the running peak exits the whole pyramid — so losses are always one leg, and winners can stack four.",
        "how": [
            "Close breaks the 20-candle high: buy leg #1.",
            "Each further +2% from the last add: buy another leg (max 3 adds).",
            "Track the highest price since entry as the peak.",
            "Price falls 3% below the peak: sell the entire stack.",
            "Losing trades cost one leg; winners can compound four.",
        ],
        "params": {
            "entry_lookback": {"what": "Breakout window for the first leg.", "effect": "Longer = bigger structural breaks."},
            "add_pct": {"what": "Advance between adds.", "effect": "Smaller = stacks faster in strong trends."},
            "max_adds": {"what": "Cap on extra legs.", "effect": "Higher = more compounding, bigger reversal risk."},
            "trail_pct": {"what": "Peak-to-exit distance.", "effect": "Tighter = protects more, exits on normal pullbacks."},
            "size_pct": {"what": "Leg size as share of starting balance.", "effect": "Bigger legs = stronger compounding and losses."},
        },
        "strengths": [
            "Asymmetric by construction: small routine losses, occasional stacked winners.",
            "The trail converts 'let winners run' into an executable rule.",
            "Multi-leg structure averages into trends at progressively better context.",
        ],
        "weaknesses": [
            "A 3% pullback in a strong trend is normal — it will exit early sometimes.",
            "Later legs buy near the top of the move if the trend is ending.",
            "Stacked exposure means a sharp reversal hurts more than a single position.",
        ],
        "when": ["Power trends with stair-step structure.", "V-shaped reversals after the final add hurt most."],
        "mistakes": [
            "Expecting every trade to pyramid — most will be single-leg exits.",
            "Loosening the trail to 5% and forgetting giveback grows too.",
            "Ignoring the add cap: unlimited adds = one reversal wipes many legs.",
        ],
        "watch": ["State shows adds and peak_price — watch the ladder stack in trends.", "Exits should come after the first 3% reversal from a visible peak."],
        "concepts": ["pyramiding", "trailing_stop", "breakout", "position_sizing", "risk_management"],
        "related": ["10_donchian_breakout", "35_chandelier_trend_ride", "36_martingale_dip"],
    },
    "38_kelly_fraction_sizer": {
        "difficulty": 3,
        "summary": "A breakout strategy whose position size is decided by mathematics: Kelly's formula from the account's own trade history — and it stands aside when the edge is negative.",
        "idea": "Most strategies decide WHEN to trade; Kelly decides HOW MUCH. This account enters Donchian(20) breakouts, then sizes the bet with the Kelly criterion estimated from its own closed trades: f* = p − (1−p)/b. No history (10 trades)? Trade small by default. Negative edge? Don't trade at all. The sizing is the intelligence.",
        "how": [
            "Close breaks the 20-candle high: candidate entry.",
            "Estimate p (win rate) and b (avg win / avg loss) from the account's closed trades.",
            "Compute full Kelly, halve it, cap at 50% of cash.",
            "Positive edge: buy sized to the fraction. No/negative edge: stand aside.",
            "Exit when close breaks the 10-candle low.",
        ],
        "params": {
            "entry_period": {"what": "Breakout window.", "effect": "20 classic turtle."},
            "exit_period": {"what": "Exit window.", "effect": "10 classic turtle."},
            "min_trades": {"what": "Closed trades before Kelly is trusted.", "effect": "Below this it trades the default 10% — small while learning."},
            "default_fraction": {"what": "Sizing before enough history.", "effect": "10% keeps the learning phase cheap."},
            "max_fraction": {"what": "Absolute cap on any Kelly bet.", "effect": "50% prevents over-betting from noisy estimates."},
            "kelly_fraction": {"what": "Share of full Kelly to bet.", "effect": "0.5 = half-Kelly: most of the growth, half the volatility."},
        },
        "strengths": [
            "Adaptive risk: sizes up only after the account proves an edge.",
            "The negative-edge stand-aside is rare and brilliant.",
            "Textbook link between trade stats and position sizing.",
        ],
        "weaknesses": [
            "Kelly from 10-30 trades is statistically shaky.",
            "In a small sample a lucky streak can justify huge sizes (cap helps).",
            "Slow to adapt: estimates update only as trades close.",
        ],
        "when": ["Long-horizon accounts where trade statistics can accumulate.", "Early on it's tiny (default 10%) — patience required."],
        "mistakes": [
            "Reading the Kelly fraction as a signal — it's a size, decided after the breakout.",
            "Expecting full-Kelly growth; this account deliberately runs half.",
            "Forgetting the stand-aside: no edge, no trade — that's a feature.",
        ],
        "watch": ["State shows the current fraction and its p/b origin.", "Watch the fraction grow after winning streaks and shrink (or zero) after losses."],
        "concepts": ["kelly", "half_kelly", "position_sizing", "risk_management", "donchian"],
        "related": ["10_donchian_breakout", "39_multi_indicator_consensus", "42_sibling_performance_allocator"],
    },
    # ------------------------------------------------------------------ #
    # Composite & Hybrid
    # ------------------------------------------------------------------ #
    "39_multi_indicator_consensus": {
        "difficulty": 2,
        "summary": "Five indicators vote, majority rules: buy at +3 of 5 bullish, sell at −3. Disagreement never gets traded.",
        "idea": "Every indicator has a blind spot — RSI lies in trends, EMAs whipsaw in chop. Instead of trusting one, this account polls five different toolboxes (RSI, EMA cross, MACD, Bollinger, StochRSI). Each casts ±1. When three or more agree, the trade has survived five independent worldviews.",
        "how": [
            "Each candle, poll the five voters: RSI(14), EMA 9/21, MACD(12/26/9), Bollinger(20,2), StochRSI(14,14,3,3).",
            "Each voter says bullish (+1), bearish (−1) or neutral (0).",
            "Score ≥ +3: buy. Score ≤ −3: sell.",
            "Scores between: no action — disagreement is information too.",
            "The state prints every vote so you can audit the score.",
        ],
        "params": {
            "threshold": {"what": "Votes required for action.", "effect": "3 of 5 = strict majority. Higher = rarer, more certain trades."},
        },
        "strengths": [
            "Filters the whipsaws that plague single-indicator systems.",
            "Auditable: every vote is recorded in live state.",
            "Teaches exactly how indicators disagree — a free education.",
        ],
        "weaknesses": [
            "The voters share inputs (all use closes) — less independent than they look.",
            "Majority rule is slow: it needs most voters to flip.",
            "In a crash all five vote bearish AFTER the fall — late by design.",
        ],
        "when": ["Markets where half the indicators are right at a time.", "Vicious trends where it arrives late but avoids false early entries."],
        "mistakes": [
            "Adding more voters for 'safety' — correlated voters just double-count.",
            "Expecting it to catch reversals early; consensus is a confirmation tool.",
            "Ignoring the individual votes in state — they show WHY it traded.",
        ],
        "watch": ["State prints all five votes + score — check the split before each trade.", "Score ±1/±2 days with no trades are the strategy working as designed."],
        "concepts": ["consensus", "oscillator", "trend", "confluence", "meta_strategy"],
        "related": ["40_trend_pullback_confluence", "03_macd_histogram_reversal", "41_volatility_regime_switcher"],
    },
    "40_trend_pullback_confluence": {
        "difficulty": 2,
        "summary": "The two-layer trade: only buy RSI dips when the long-term trend (SMA200 > SMA50) says the market is still up.",
        "idea": "Naked RSI dip-buying catches falling knives in bear markets. This account fixes that with a gate: only buy weakness (RSI < 35) while price trades above the SMA200 with SMA50 above SMA200 — i.e., dips inside an uptrend. Selling requires RSI > 65 OR losing the SMA50. Trend and timing filters in series.",
        "how": [
            "Trend gate: price above SMA200 AND SMA50 > SMA200 (long-term up).",
            "Dip trigger: RSI(14) < 35 while the gate is open: buy.",
            "Ride the recovery while the trend holds.",
            "Exit when RSI > 65 (recovered) or price loses the SMA50.",
        ],
        "params": {
            "trend_period": {"what": "The macro trend line.", "effect": "200: only true regimes pass."},
            "mid_period": {"what": "The trend-health line whose loss exits.", "effect": "50 balances early exits vs protection."},
            "rsi_period": {"what": "Dip oscillator length.", "effect": "14 standard."},
            "rsi_buy": {"what": "Weakness required to buy.", "effect": "Lower = only deeper dips inside trends."},
            "rsi_sell": {"what": "Recovery that ends the trade.", "effect": "Higher = rides the full bounce."},
        },
        "strengths": [
            "The single best conceptual fix for dip-buying: context above trigger.",
            "Buys in uptrends only — the exact opposite of catching knives.",
            "Clear two-layer logic that generalizes to any strategy pair.",
        ],
        "weaknesses": [
            "200-candle warm-up and a strict gate = few signals.",
            "A genuine trend break (price under SMA200) happens AFTER damage.",
            "Two SMA filters are slower than one — exits lag.",
        ],
        "when": ["Long uptrends with healthy pullbacks — its home turf.", "Bear markets: gate closed, account idle in cash (correct)."],
        "mistakes": [
            "Buying RSI dips without the gate — that's just strategy 01 again.",
            "Expecting it to short or fade the breakdown; it only holds cash.",
            "Ignoring that 'price above SMA200' uses current price — a daily close below flips it.",
        ],
        "watch": ["The gate state (trend up/down) should visibly close during corrections.", "Entries should be rare and only after shallow dips in uptrends."],
        "concepts": ["confluence", "pullback", "rsi", "sma", "trend"],
        "related": ["32_fibonacci_pullback", "01_rsi_mean_reversion", "04_triple_moving_average"],
    },
    "41_volatility_regime_switcher": {
        "difficulty": 3,
        "summary": "One account, two strategies, chosen by the market's mood: high volatility → fade with Bollinger; low volatility → break out with Donchian; in between → do nothing.",
        "idea": "Different market states demand different tools. When ATR sits in the top 30% of its own history, ranges are wide and mean reversion works — so it fades with Bollinger. In the bottom 30%, compression precedes breakouts — so it trades Donchian breaks. The middle 40% is noise: it sits out entirely.",
        "how": [
            "Measure ATR(14)'s percentile rank over 100 candles.",
            "Percentile ≥ 70 (high vol): switch to mean-reversion mode — buy closes below the Bollinger lower band, exit at the middle band.",
            "Percentile ≤ 30 (low vol): switch to breakout mode — buy closes above the 20-candle Donchian high, exit below the 10-candle low.",
            "30-70 (neutral): no trades at all.",
            "State prints the current percentile and active regime.",
        ],
        "params": {
            "atr_period": {"what": "ATR lookback for the regime meter.", "effect": "14 standard."},
            "percentile_lookback": {"what": "History for ranking ATR.", "effect": "100 candles gives a stable 'normal'."},
            "high_vol": {"what": "Percentile that means 'high volatility'.", "effect": "Higher = only truly wild markets fade; lower = fades more often."},
            "low_vol": {"what": "Percentile that means 'low volatility'.", "effect": "Lower = only deep compressions break out."},
            "bb_period": {"what": "Bollinger lookback in fade mode.", "effect": "20 standard."},
            "bb_mult": {"what": "Band width in fade mode.", "effect": "2 standard."},
            "entry_period": {"what": "Donchian high window in breakout mode.", "effect": "20 standard."},
            "exit_period": {"what": "Donchian low window in breakout mode.", "effect": "10 standard."},
        },
        "strengths": [
            "Regime awareness is the future of systematic trading — this is its simplest honest form.",
            "Both sub-strategies run only in the state where they're historically strong.",
            "The neutral dead-zone prevents chop whipsaws by design.",
        ],
        "weaknesses": [
            "Regime switches lag: by the time ATR percentile confirms, half the move is gone.",
            "Two full sub-strategies to debug.",
            "Percentile windows are fixed — regime 'normal' drifts over years.",
        ],
        "when": ["Alternating volatile/quiet phases — it catches both.", "In-between regimes: nothing (the 40% dead zone is deliberate)."],
        "mistakes": [
            "Expecting it to trade every day — the dead zone is the design.",
            "Treating mode labels as predictions; they describe the last 100 candles.",
            "Tuning high_vol/low_vol so the dead zone disappears — that's removing the filter.",
        ],
        "watch": ["State shows ATR percentile and regime — see it flip after volatility bursts.", "Fade-mode entries during wild candles, breakout-mode entries after quiet ones."],
        "concepts": ["regime_switching", "atr", "bollinger", "donchian", "volatility", "meta_strategy"],
        "related": ["29_volatility_squeeze", "06_bollinger_mean_reversion", "10_donchian_breakout"],
    },
    "42_sibling_performance_allocator": {
        "difficulty": 3,
        "summary": "The crowd-surfer meta-strategy: trade only while the median of the other 41 accounts is making money; ride the leader, stand aside in the slump.",
        "idea": "The ultimate regime filter is the bot itself: when the median sibling account is profitable, the market is tradeable; when the majority of 41 systems are underwater, it isn't. This account reads (never touches) its siblings' equity, participates while the ensemble median ≥ 0, and mirrors the best performer's behaviour.",
        "how": [
            "Each tick, read the return of all 41 sibling accounts.",
            "Compute the ensemble median return (and find the current leader).",
            "Median ≥ 0: the market is tradeable — buy in.",
            "Median < 0: the ensemble is bleeding — stand aside in cash.",
            "State prints median, peer count and leader for full transparency.",
        ],
        "params": {
            "momentum_lookback": {"what": "Reserved window for momentum measurement (kept for tuning).", "effect": "Not used by the current default logic — a placeholder for experimentation."},
            "median_floor_pct": {"what": "Median sibling return required to participate.", "effect": "0 = trade while the median sibling is at break-even or better. Raise it to demand a healthier ensemble."},
        },
        "strengths": [
            "A real ensemble/meta signal — 41 diverse strategies voting with their equity.",
            "Completely mechanical market-health filter.",
            "Deliberately documented exception to isolation, and read-only.",
        ],
        "weaknesses": [
            "Correlated siblings (many trend accounts) make the median less diverse than it looks.",
            "It participates when the median is fine but can still pick a bad moment.",
            "Conceptually subtle — the hardest strategy in the zoo to explain quickly.",
        ],
        "when": ["Any market — it adapts through the ensemble itself.", "The ensemble is only as smart as its weakest correlated cluster."],
        "mistakes": [
            "Judging it by its own curve — it's a meta-bet on the whole experiment.",
            "Forgetting it does NOT copy the leader's trades; it rides 'participate/stand aside' only.",
            "Reading its flat periods as failure — standing aside IS the strategy when the ensemble bleeds.",
        ],
        "watch": ["State prints median_return_pct and leader — compare with the portfolio's total return.", "It should be flat during portfolio-wide slumps and active during broad rallies."],
        "concepts": ["allocation", "ensemble", "meta_strategy", "risk_management", "mean_reversion"],
        "related": ["39_multi_indicator_consensus", "41_volatility_regime_switcher", "38_kelly_fraction_sizer"],
    },
    # ------------------------------------------------------------------ #
    # Mean Reversion & Channels (finish)
    # ------------------------------------------------------------------ #
    "06_bollinger_mean_reversion": {
        "difficulty": 1,
        "summary": "The rubber-band trade: buy when price closes below the lower Bollinger band; sell when it snaps back to the middle.",
        "idea": "Bollinger bands wrap price in a statistically defined envelope. A close below the lower band means the fall is 2 standard deviations from the mean — unusually stretched. Rubber bands snap back; this account buys the stretch and exits at the mean (middle band), taking the statistical middle and leaving the tails.",
        "how": [
            "Compute Bollinger(20, 2): middle SMA +/− 2 stdevs.",
            "Close below the LOWER band: buy (stretched down).",
            "Hold while price recovers toward the mean.",
            "Close reaches the MIDDLE band: sell (reversion complete).",
            "No stops, no targets — the bands define everything.",
        ],
        "params": {
            "period": {"what": "SMA/stdev lookback.", "effect": "20 standard; shorter reacts faster."},
            "mult": {"what": "Band width in standard deviations.", "effect": "2 = ~95% of closes inside. Higher = rarer, more extreme touches."},
        },
        "strengths": [
            "Statistical basis: touches beyond 2σ are genuinely unusual.",
            "Self-scaling to volatility — bands widen in storms.",
            "Objective exit (middle band) removes greed.",
        ],
        "weaknesses": [
            "Trends ride the lower band for days — 'stretched' keeps stretching.",
            "No trend/regime filter (strategy 41 fixes exactly this).",
            "Sells at the mean, leaving the second half of bounces on the table.",
        ],
        "when": ["Range markets with wide, honest swings.", "Strong downtrends are its classic failure mode."],
        "mistakes": [
            "Buying every lower-band touch in a crash (add strategy 40's gate mentally).",
            "Expecting the upper band to matter — exits are at the middle band only.",
            "Forgetting stdev on 20 candles is itself jumpy.",
        ],
        "watch": ["Entries should be visible as closes poking below the lower band on the Market screen.", "Exits at the middle band — quick round trips in healthy ranges."],
        "concepts": ["bollinger", "mean_reversion", "volatility", "oscillator"],
        "related": ["01_rsi_mean_reversion", "24_zscore_mean_reversion", "29_volatility_squeeze"],
    },
    "07_keltner_breakout": {
        "difficulty": 2,
        "summary": "Volatility-expansion breakout: buy closes above the ATR-scaled upper Keltner band; exit when price falls back under the middle EMA.",
        "idea": "Keltner bands size their width with ATR, so the upper band marks 'price moved more than typical ranges allow' — a volatility expansion, not just a statistical stretch. When a close lands beyond it, real energy arrived. This account joins expansions and leaves when price re-enters the channel.",
        "how": [
            "Compute Keltner(20, 2): middle EMA(20) +/− 2×ATR(20).",
            "Close ABOVE the upper band: buy (genuine expansion).",
            "Hold while price trades above the middle EMA.",
            "Close falls back BELOW the middle EMA: sell.",
        ],
        "params": {
            "period": {"what": "EMA + ATR lookback.", "effect": "20 standard."},
            "mult": {"what": "Band width in ATRs.", "effect": "2 = two typical ranges beyond the EMA; higher = only huge expansions."},
        },
        "strengths": [
            "ATR scaling reads the market's actual recent behaviour.",
            "Catches real volatility expansions early.",
            "Clean middle-band exit locks in the expansion's core.",
        ],
        "weaknesses": [
            "Upper-band closes can be exhaustion spikes, not starts.",
            "EMA middle exits early in strong trends (price rarely returns).",
            "Category 'Mean Reversion & Channels' but behaves like a breakout account.",
        ],
        "when": ["Volatility bursts after quiet periods.", "Slow trends that never leave the channel produce nothing."],
        "mistakes": [
            "Confusing it with Bollinger fades — same shape, opposite philosophy.",
            "Expecting ATR and stdev bands to agree; they measure different things.",
            "Buying wicks above the band — the rule is a CLOSE above.",
        ],
        "watch": ["Entries should follow wide-range candles that exit the channel on the chart.", "Compare its trades with strategy 06 — one buys the outside, the other the return."],
        "concepts": ["keltner", "atr", "breakout", "volatility"],
        "related": ["06_bollinger_mean_reversion", "10_donchian_breakout", "29_volatility_squeeze"],
    },
    "08_stoch_rsi_reversal": {
        "difficulty": 2,
        "summary": "Extreme-of-the-extreme: buy when StochRSI %K turns back above %D while still below 20; sell the mirrored high-side cross.",
        "idea": "RSI can look oversold for weeks. StochRSI measures where RSI itself sits in its own range — sub-20 means RSI is at a short-term extreme even by RSI standards. Buying the %K/%D cross in that zone catches the exact turn of an extreme oscillator.",
        "how": [
            "Compute StochRSI: RSI(14) → stochastic(14) → %K(3), %D = SMA(%K,3).",
            "Buy when %K crosses ABOVE %D while %K was ≤ 20 (oversold turn).",
            "Ride the oscillator recovery.",
            "Sell when %K crosses BELOW %D while %K was ≥ 80.",
        ],
        "params": {
            "rsi_period": {"what": "Base RSI length.", "effect": "14 standard."},
            "stoch_period": {"what": "Window ranking RSI's range.", "effect": "14 standard."},
            "k_period": {"what": "Smoothing of raw StochRSI.", "effect": "3 standard."},
            "d_period": {"what": "Smoothing of %K into %D.", "effect": "3 standard."},
            "oversold": {"what": "Zone where the buy cross must occur.", "effect": "Lower = only deeper RSI extremes."},
            "overbought": {"what": "Zone where the sell cross must occur.", "effect": "Higher = stricter sell zone."},
        },
        "strengths": [
            "Double-filtered extremes are rarer and more meaningful.",
            "Cross-based entries avoid buying while the oscillator still falls.",
            "Standard parameters, widely studied.",
        ],
        "weaknesses": [
            "Layers of smoothing = late signals relative to raw price.",
            "In strong trends StochRSI pins at extremes; crosses misfire or never come.",
            "Four smoothing parameters are hard to reason about end-to-end.",
        ],
        "when": ["Sharp but short-lived oversold spells.", "Slow grinds keep StochRSI mid-range (few signals)."],
        "mistakes": [
            "Buying %K < 20 without the %D cross — the cross is the turn evidence.",
            "Expecting RSI-level semantics; 20 here is extreme-for-RSI, not RSI=20.",
            "Tuning only one of the four periods without the others.",
        ],
        "watch": ["State shows %K and %D — entries should follow their sub-20 crossovers.", "Check which candles produced the extreme: volume spikes make them more reliable."],
        "concepts": ["stoch_rsi", "rsi", "oscillator", "mean_reversion"],
        "related": ["21_williams_r_reversal", "01_rsi_mean_reversion", "39_multi_indicator_consensus"],
    },
}
